### ISSUE TITLE
新学期显示的课表信息还是上个学期的

### ISSUE THREAD

**Issue by AotoriChiaki** [Icear/SimpleClass#2]
RT

**Comment by Icear** [comment]
- SimpleClass对林大课程的读取流程是直接访问“学期理论课表”页，并提取所显示的课程表，所以提取到的课程表对应学期是根据教务处默认显示的课表来显示的
- 看了一下林大教务处的默认显示课表现在还是上学期的，所以app内也没有更新
- **解决方案的话，以后会加入主动选择要提取学期的功能，目前只能等待教务处更新默认课表(开学时会更新**

**Comment by Icear** [comment]
今天教务处已更新，app可以正常导入了

**Comment by Icear** [comment]
但是app发现另外一个问题，对应的时间表尚未更新会导致导入的日历时间不正确，请暂时不要使用………

**Comment by Icear** [comment]
- 已在近期commit中增加了手动选择学期的流程，在导入课程表时可以手动指定要读取课程表的学期
- 新的版本预计在本周末会发布，同时修复新学期导入数据不准确的问题，详见 issue #3
